# Generated by Django 5.2.4 on 2025-09-16 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('crime_type', models.CharField(choices=[('Phishing', 'Phishing'), ('Identity Theft', 'Identity Theft'), ('Online Fraud', 'Online Fraud'), ('Hacking', 'Hacking'), ('Cyberstalking', 'Cyberstalking'), ('Malware/Ransomware', 'Malware/Ransomware'), ('Others', 'Others')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date_of_crime', models.DateField()),
                ('victim_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Investigation', 'Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
